import { RNG } from '@/lib/rng';
import { Rational, gcd, lcm } from '@/lib/rational';
import {
  type Template,
  type GeneratedItem,
  markNumeric,
  choiceItem,
  commas,
  inWords,
} from '@/lib/engine';

// Every answer below is computed by code, never written out by hand and never
// produced by a language model. Distractors are generated by applying a named
// misconception, so a wrong answer tells us which one fired.

const money = (r: Rational) => '£' + (r.value).toFixed(2);

function t(
  id: string,
  objectiveId: string,
  difficulty: 1 | 2 | 3 | 4 | 5,
  transfer: 0 | 1 | 2 | 3,
  generate: (rng: RNG) => GeneratedItem
): Template {
  return { id, objectiveId, difficulty, transfer, generate };
}

export const MATHS_TEMPLATES: Template[] = [
  // ============================================================ place value
  t('M.PV.READ.figures', 'M.PV.READ', 2, 0, (rng) => {
    const n = rng.int(100_000, 9_999_999);
    return {
      templateId: 'M.PV.READ.figures',
      objectiveId: 'M.PV.READ',
      seed: 0,
      input: 'number',
      stem: `Write this number in figures.\n\n${inWords(n)}`,
      note: 'Millions, then thousands, then the rest.',
      canonical: commas(n),
      working: [
        { say: `Split it into groups: millions, thousands, then the rest.` },
        { say: `${inWords(n)}` },
        { say: `= ${commas(n)}` },
      ],
      mark: markNumeric(new Rational(n)),
    };
  }),

  t('M.PV.READ.largest', 'M.PV.READ', 2, 1, (rng) => {
    const base = rng.int(1_000_000, 8_000_000);
    const digits = String(base).split('');
    // Four numbers with the same digit count, differing at different columns.
    const cands = new Set<number>([base]);
    while (cands.size < 4) {
      const d = digits.slice();
      const pos = rng.int(0, d.length - 2);
      d[pos] = String(rng.int(0, 9));
      const v = parseInt(d.join(''), 10);
      if (v >= 1_000_000) cands.add(v);
    }
    const list = Array.from(cands);
    const max = Math.max(...list);
    // The place-shift error: comparing from the wrong end, so the one whose
    // last three digits are biggest looks like the winner.
    const byTail = list.slice().sort((a, b) => (b % 1000) - (a % 1000))[0];
    return choiceItem(
      {
        templateId: 'M.PV.READ.largest',
        objectiveId: 'M.PV.READ',
        seed: 0,
        stem: `Which of these is the largest number?`,
        working: [
          { say: `Line them up and compare from the left, not the right.` },
          { say: `${commas(byTail)} has the biggest ending, which is exactly the trap.` },
          { say: `The first column where they differ from the left decides it.` },
          { say: `= ${commas(max)}` },
        ],
        options: list.map((v) => ({
          label: commas(v),
          correct: v === max,
          // Every distractor here comes from comparing digits from the wrong
          // end, or stopping at the first column that differs by eye.
          misconceptionId: v === max ? undefined : 'place-shift',
        })),
      },
      rng
    );
  }),

  t('M.PV.DIGIT.value', 'M.PV.DIGIT', 2, 0, (rng) => {
    const digits: number[] = [];
    for (let i = 0; i < 7; i++) digits.push(rng.int(i === 0 ? 1 : 0, 9));
    const n = parseInt(digits.join(''), 10);
    // Never the leading digit (too easy) and never a zero (every misconception
    // would then produce the same answer, which teaches nothing).
    const inner = [1, 2, 3, 4, 5].filter((i) => digits[i] !== 0);
    const candidates = inner.length ? inner : [0];
    const pos = rng.pick(candidates);
    const d = digits[pos];
    const power = Math.pow(10, 6 - pos);
    const value = d * power;
    return {
      templateId: 'M.PV.DIGIT.value',
      objectiveId: 'M.PV.DIGIT',
      seed: 0,
      input: 'number',
      stem: `${commas(n)}\n\nWhat is the ${ordinalWord(pos)} digit from the left worth?`,
      note: `That digit is the ${d}.`,
      canonical: commas(value),
      working: [
        { say: `Count the columns from the right: units, tens, hundreds, thousands, ten thousands, hundred thousands, millions.` },
        { say: `The ${d} is sitting in the ${columnName(6 - pos)} column.` },
        { say: `${d} × ${commas(power)} = ${commas(value)}` },
      ],
      mark: markNumeric(new Rational(value), {
        traps: [
          { value: String(d), misconceptionId: 'face-value' },
          { value: String(d * power * 10), misconceptionId: 'off-by-one-column' },
          { value: String(Math.round((d * power) / 10)), misconceptionId: 'off-by-one-column' },
        ],
      }),
    };
  }),

  t('M.PV.ROUND.to', 'M.PV.ROUND', 2, 0, (rng) => {
    const power = rng.pick([10, 100, 1000, 10000, 100000]);
    const n = rng.int(power * 3, 9_999_999);
    const rounded = Math.round(n / power) * power;
    const truncated = Math.floor(n / power) * power;
    const wrongCol = Math.round(n / (power * 10)) * power * 10;
    return {
      templateId: 'M.PV.ROUND.to',
      objectiveId: 'M.PV.ROUND',
      seed: 0,
      input: 'number',
      stem: `Round ${commas(n)} to the nearest ${commas(power)}.`,
      canonical: commas(rounded),
      working: [
        { say: `Find the ${columnName(Math.log10(power))} column, then look at the digit just to its right.` },
        { say: `That digit is ${Math.floor((n % power) / (power / 10))}, so it rounds ${(n % power) >= power / 2 ? 'up' : 'down'}.` },
        { say: `= ${commas(rounded)}` },
      ],
      mark: markNumeric(new Rational(rounded), {
        traps: [
          { value: String(truncated), misconceptionId: 'round-down-always' },
          { value: String(wrongCol), misconceptionId: 'wrong-column' },
        ],
      }),
    };
  }),

  t('M.PV.ESTIMATE.product', 'M.PV.ESTIMATE', 3, 1, (rng) => {
    const a = rng.int(1200, 9800);
    const b = rng.int(12, 89);
    const ra = Math.round(a / 1000) * 1000;
    const rb = Math.round(b / 10) * 10;
    const est = ra * rb;
    return {
      templateId: 'M.PV.ESTIMATE.product',
      objectiveId: 'M.PV.ESTIMATE',
      seed: 0,
      input: 'number',
      stem: `Estimate ${commas(a)} × ${b}.\n\nRound the first number to the nearest thousand and the second to the nearest ten, then multiply.`,
      canonical: commas(est),
      working: [
        { say: `${commas(a)} rounds to ${commas(ra)}.` },
        { say: `${b} rounds to ${rb}.` },
        { say: `${commas(ra)} × ${rb} = ${commas(est)}` },
      ],
      mark: markNumeric(new Rational(est), {
        traps: [{ value: String(a * b), misconceptionId: 'exact-not-estimate' }],
      }),
    };
  }),

  // ============================================================ negatives
  t('M.NEG.LINE.fall', 'M.NEG.LINE', 2, 0, (rng) => {
    const start = rng.int(-8, 9);
    const fall = rng.int(3, 14);
    const end = start - fall;
    return {
      templateId: 'M.NEG.LINE.fall',
      objectiveId: 'M.NEG.LINE',
      seed: 0,
      input: 'number',
      stem: `The temperature is ${start}°C. Overnight it falls by ${fall} degrees.\n\nWhat is the temperature in the morning?`,
      unit: '°C',
      canonical: String(end),
      working: [
        { say: `Start at ${start} on a number line.` },
        { say: `Count ${fall} places to the left, going through zero.` },
        { say: `= ${end}°C` },
      ],
      mark: markNumeric(new Rational(end), {
        traps: [
          { value: String(start + fall), misconceptionId: 'towards-zero' },
          { value: String(Math.abs(end)), misconceptionId: 'ignored-sign' },
          { value: String(Math.abs(Math.abs(start) - fall)), misconceptionId: 'subtracted-magnitudes' },
        ],
      }),
    };
  }),

  t('M.NEG.LINE.gap', 'M.NEG.LINE', 3, 1, (rng) => {
    const low = rng.int(-14, -2);
    const high = rng.int(1, 12);
    const gap = high - low;
    return {
      templateId: 'M.NEG.LINE.gap',
      objectiveId: 'M.NEG.LINE',
      seed: 0,
      input: 'number',
      stem: `In one night the temperature went from ${high}°C down to ${low}°C.\n\nHow many degrees did it fall?`,
      canonical: String(gap),
      working: [
        { say: `From ${high} down to 0 is ${high} degrees.` },
        { say: `From 0 down to ${low} is another ${Math.abs(low)} degrees.` },
        { say: `${high} + ${Math.abs(low)} = ${gap}` },
      ],
      mark: markNumeric(new Rational(gap), {
        traps: [
          { value: String(Math.abs(high - Math.abs(low))), misconceptionId: 'subtracted-magnitudes' },
          { value: String(low - high), misconceptionId: 'ignored-sign' },
        ],
      }),
    };
  }),

  // ============================================================ decimals
  t('M.DEC.PLACE.value', 'M.DEC.PLACE', 2, 0, (rng) => {
    const whole = rng.int(1, 9);
    const dec = [rng.int(0, 9), rng.int(0, 9), rng.int(1, 9)];
    // dec[2] is always 1 to 9, so this list is never empty.
    const pos = rng.pick([0, 1, 2].filter((i) => dec[i] !== 0));
    const d = dec[pos];
    const den = Math.pow(10, pos + 1);
    const value = new Rational(d, den);
    const shown = `${whole}.${dec.join('')}`;
    const names = ['tenths', 'hundredths', 'thousandths'];
    return {
      templateId: 'M.DEC.PLACE.value',
      objectiveId: 'M.DEC.PLACE',
      seed: 0,
      input: 'number',
      stem: `${shown}\n\nWhat is the digit in the ${names[pos]} column worth?`,
      note: `That is the ${['first', 'second', 'third'][pos]} digit after the point. Answer as a decimal.`,
      canonical: value.toDecimal() ?? value.toString(),
      working: [
        { say: `After the point the columns are tenths, hundredths, thousandths.` },
        { say: `The ${d} is in the ${names[pos]} column.` },
        { say: `= ${d} ${names[pos]} = ${value.toDecimal()}` },
      ],
      mark: markNumeric(value, {
        traps: [
          { value: String(d), misconceptionId: 'face-value' },
          { value: new Rational(d, den * 10).toDecimal() ?? '0', misconceptionId: 'off-by-one-column' },
          { value: new Rational(d, Math.max(1, den / 10)).toDecimal() ?? '0', misconceptionId: 'off-by-one-column' },
        ],
      }),
    };
  }),

  t('M.DEC.PLACE.bigger', 'M.DEC.PLACE', 2, 1, (rng) => {
    // One short decimal, one long decimal, engineered so the longer one is smaller.
    const a = new Rational(rng.int(2, 8), 10); // e.g. 0.4
    const bTenths = rng.int(0, a.n - 1);
    const b = new Rational(bTenths * 100 + rng.int(10, 99), 1000); // e.g. 0.283
    const bigger = a.cmp(b) > 0 ? a : b;
    const smaller = a.cmp(b) > 0 ? b : a;
    return choiceItem(
      {
        templateId: 'M.DEC.PLACE.bigger',
        objectiveId: 'M.DEC.PLACE',
        seed: 0,
        stem: `Which of these is bigger?`,
        working: [
          { say: `Compare the tenths column first: ${a.toDecimal()} has ${a.n} tenths, ${b.toDecimal()} has ${Math.floor(b.value * 10)}.` },
          { say: `Extra digits after the point do not make a number bigger.` },
          { say: `= ${bigger.toDecimal()}` },
        ],
        options: [
          { label: bigger.toDecimal() ?? '', correct: true },
          { label: smaller.toDecimal() ?? '', correct: false, misconceptionId: 'longer-decimal-bigger' },
        ],
      },
      rng
    );
  }),

  t('M.DEC.X10.shift', 'M.DEC.X10', 2, 0, (rng) => {
    const power = rng.pick([10, 100, 1000]);
    const up = rng.bool();
    const base = new Rational(rng.int(101, 9989), 100); // two decimal places
    const answer = up ? base.mul(new Rational(power)) : base.div(new Rational(power));
    const wrongDir = up ? base.div(new Rational(power)) : base.mul(new Rational(power));
    const wrongMag = up ? base.mul(new Rational(power * 10)) : base.div(new Rational(power * 10));
    const cols = Math.log10(power);
    return {
      templateId: 'M.DEC.X10.shift',
      objectiveId: 'M.DEC.X10',
      seed: 0,
      input: 'number',
      stem: `${base.toDecimal()} ${up ? '×' : '÷'} ${power} = ?`,
      canonical: answer.toDecimal() ?? answer.toString(),
      working: [
        { say: `${power} means ${cols} column${cols === 1 ? '' : 's'}.` },
        { say: `Every digit moves ${cols} place${cols === 1 ? '' : 's'} to the ${up ? 'left' : 'right'}. The point does not move.` },
        { say: `= ${answer.toDecimal()}` },
      ],
      mark: markNumeric(answer, {
        traps: [
          { value: wrongDir.toDecimal() ?? '0', misconceptionId: 'wrong-direction' },
          { value: wrongMag.toDecimal() ?? '0', misconceptionId: 'wrong-magnitude' },
        ],
      }),
    };
  }),

  // ============================================================ factors, multiples, primes
  t('M.FAC.FACTORS.hcf', 'M.FAC.FACTORS', 3, 0, (rng) => {
    const g = rng.pick([2, 3, 4, 6, 8, 9, 12]);
    let p = rng.int(2, 9);
    let q = rng.int(2, 9);
    while (gcd(p, q) !== 1 || p === q) {
      p = rng.int(2, 9);
      q = rng.int(2, 11);
    }
    const a = g * p;
    const b = g * q;
    const hcf = gcd(a, b);
    const smaller = Math.min(...divisorsOf(hcf).filter((d) => d < hcf && d > 1), 1);
    return {
      templateId: 'M.FAC.FACTORS.hcf',
      objectiveId: 'M.FAC.FACTORS',
      seed: 0,
      input: 'number',
      stem: `What is the highest common factor of ${a} and ${b}?`,
      canonical: String(hcf),
      working: [
        { say: `Factors of ${a}: ${divisorsOf(a).join(', ')}` },
        { say: `Factors of ${b}: ${divisorsOf(b).join(', ')}` },
        { say: `The biggest one in both lists is ${hcf}.` },
      ],
      mark: markNumeric(new Rational(hcf), {
        traps: [
          { value: String(a * b), misconceptionId: 'factor-multiple-swap' },
          ...(smaller > 1 ? [{ value: String(smaller), misconceptionId: 'missed-pair' }] : []),
        ],
      }),
    };
  }),

  t('M.FAC.FACTORS.which', 'M.FAC.FACTORS', 2, 1, (rng) => {
    const n = rng.pick([24, 36, 40, 48, 54, 60, 72]);
    const facs = divisorsOf(n).filter((d) => d > 1 && d < n);
    const correct = rng.pick(facs);
    const mults = [n * 2, n * 3, n + n / 2].filter((m) => !facs.includes(m));
    const opts = [
      { label: String(correct), correct: true },
      { label: String(mults[0]), correct: false, misconceptionId: 'factor-multiple-swap' },
      { label: String(mults[1]), correct: false, misconceptionId: 'factor-multiple-swap' },
      { label: String(nearestNonFactor(n, rng)), correct: false, misconceptionId: 'near-factor' },
    ];
    return choiceItem(
      {
        templateId: 'M.FAC.FACTORS.which',
        objectiveId: 'M.FAC.FACTORS',
        seed: 0,
        stem: `Which of these is a factor of ${n}?`,
        note: 'A factor divides into it exactly, with nothing left over.',
        working: [
          { say: `${n} ÷ ${correct} = ${n / correct}, exactly.` },
          { say: `The bigger numbers are multiples of ${n}, not factors of it.` },
          { say: `= ${correct}` },
        ],
        options: opts,
      },
      rng
    );
  }),

  t('M.FAC.MULT.lcm', 'M.FAC.MULT', 3, 0, (rng) => {
    const a = rng.int(4, 12);
    let b = rng.int(4, 15);
    while (b === a) b = rng.int(4, 15);
    const l = lcm(a, b);
    return {
      templateId: 'M.FAC.MULT.lcm',
      objectiveId: 'M.FAC.MULT',
      seed: 0,
      input: 'number',
      stem: `What is the smallest number that both ${a} and ${b} divide into exactly?`,
      canonical: String(l),
      working: [
        { say: `Multiples of ${a}: ${listMultiples(a, l)}` },
        { say: `Multiples of ${b}: ${listMultiples(b, l)}` },
        { say: `The first one that appears in both lists is ${l}.` },
      ],
      mark: markNumeric(new Rational(l), {
        traps: [
          ...(a * b !== l ? [{ value: String(a * b), misconceptionId: 'product-not-lcm' }] : []),
          { value: String(gcd(a, b)), misconceptionId: 'factor-multiple-swap' },
        ],
      }),
    };
  }),

  t('M.FAC.PRIME.which', 'M.FAC.PRIME', 2, 0, (rng) => {
    const primes = [11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97];
    const oddComposites = [9, 15, 21, 25, 27, 33, 35, 39, 45, 49, 51, 55, 57, 63, 65, 69, 77, 81, 85, 87, 91, 93, 95];
    const p = rng.pick(primes);
    const [c1, c2] = rng.sample(oddComposites, 2);
    return choiceItem(
      {
        templateId: 'M.FAC.PRIME.which',
        objectiveId: 'M.FAC.PRIME',
        seed: 0,
        stem: `Which of these is a prime number?`,
        note: 'A prime has exactly two factors: itself and 1.',
        working: [
          { say: `${c1} = ${smallestFactor(c1)} × ${c1 / smallestFactor(c1)}, so it has more than two factors.` },
          { say: `${c2} = ${smallestFactor(c2)} × ${c2 / smallestFactor(c2)}, so it does too.` },
          { say: `1 only has one factor, so it does not count.` },
          { say: `= ${p}` },
        ],
        options: [
          { label: String(p), correct: true },
          { label: String(c1), correct: false, misconceptionId: 'odd-means-prime' },
          { label: String(c2), correct: false, misconceptionId: 'odd-means-prime' },
          { label: '1', correct: false, misconceptionId: 'one-is-prime' },
        ],
      },
      rng
    );
  }),

  // ============================================================ fractions
  t('M.FR.SIMPLIFY.basic', 'M.FR.SIMPLIFY', 2, 0, (rng) => {
    const base = rng.pick([
      [1, 2], [1, 3], [2, 3], [1, 4], [3, 4], [1, 5], [2, 5], [3, 5], [4, 5],
      [1, 6], [5, 6], [3, 8], [5, 8], [7, 8], [2, 9], [4, 9], [7, 10], [9, 10],
    ]);
    const k = rng.int(2, 7);
    const n = base[0] * k;
    const d = base[1] * k;
    const answer = new Rational(n, d);
    const halfway = k % 2 === 0 ? new Rational(n / 2, d / 2) : null;
    return {
      templateId: 'M.FR.SIMPLIFY.basic',
      objectiveId: 'M.FR.SIMPLIFY',
      seed: 0,
      input: 'fraction',
      stem: `Simplify ${n}/${d}.`,
      note: 'Give it in its simplest form.',
      canonical: answer.toString(),
      working: [
        { say: `What divides into both ${n} and ${d}? The highest is ${k}.` },
        { say: `${n} ÷ ${k} = ${base[0]} and ${d} ÷ ${k} = ${base[1]}.` },
        { say: `= ${answer.toString()}` },
      ],
      mark: markNumeric(answer, {
        requireSimplest: true,
        traps: [
          ...(halfway && !halfway.eq(answer) ? [{ value: `${n / 2}/${d / 2}`, misconceptionId: 'not-simplified' }] : []),
          { value: `${n - 1}/${d - 1}`, misconceptionId: 'subtract-not-divide' },
        ],
      }),
    };
  }),

  t('M.FR.COMMON.denominator', 'M.FR.COMMON', 3, 0, (rng) => {
    const d1 = rng.pick([2, 3, 4, 5, 6, 8, 10]);
    let d2 = rng.pick([2, 3, 4, 5, 6, 8, 9, 10, 12]);
    while (d2 === d1) d2 = rng.pick([2, 3, 4, 5, 6, 8, 9, 10, 12]);
    const n1 = rng.int(1, d1 - 1);
    const n2 = rng.int(1, d2 - 1);
    const l = lcm(d1, d2);
    return {
      templateId: 'M.FR.COMMON.denominator',
      objectiveId: 'M.FR.COMMON',
      seed: 0,
      input: 'number',
      stem: `You want to rewrite ${n1}/${d1} and ${n2}/${d2} so they have the same bottom number.\n\nWhat is the smallest bottom number you can use?`,
      canonical: String(l),
      working: [
        { say: `You need a number both ${d1} and ${d2} divide into.` },
        { say: `Multiples of ${d1}: ${[1, 2, 3, 4, 5].map((k) => d1 * k).join(', ')}, …` },
        { say: `The smallest that ${d2} also goes into is ${l}.` },
      ],
      mark: markNumeric(new Rational(l), {
        traps: [
          { value: String(d1 + d2), misconceptionId: 'added-denominators' },
          ...(d1 * d2 !== l ? [{ value: String(d1 * d2), misconceptionId: 'product-not-lcm' }] : []),
        ],
      }),
    };
  }),

  t('M.FR.COMMON.scale', 'M.FR.COMMON', 3, 1, (rng) => {
    const d = rng.pick([2, 3, 4, 5, 6, 8]);
    const n = rng.int(1, d - 1);
    const k = rng.int(2, 6);
    const target = d * k;
    const answer = n * k;
    return {
      templateId: 'M.FR.COMMON.scale',
      objectiveId: 'M.FR.COMMON',
      seed: 0,
      input: 'number',
      stem: `${n}/${d} = ?/${target}\n\nWhat goes on the top?`,
      canonical: String(answer),
      working: [
        { say: `${d} × ${k} = ${target}, so the bottom was multiplied by ${k}.` },
        { say: `Whatever you do to the bottom you must do to the top.` },
        { say: `${n} × ${k} = ${answer}` },
      ],
      mark: markNumeric(new Rational(answer), {
        traps: [
          { value: String(n), misconceptionId: 'bottom-only' },
          { value: String(n + k), misconceptionId: 'subtract-not-divide' },
        ],
      }),
    };
  }),

  t('M.FR.COMPARE.pair', 'M.FR.COMPARE', 2, 0, (rng) => {
    // Deliberately built so the fraction with the bigger bottom number is smaller.
    const d1 = rng.pick([3, 4, 5, 6]);
    const d2 = rng.pick([8, 9, 10, 12]);
    const a = new Rational(1, d1);
    const b = new Rational(1, d2);
    const bigger = a.cmp(b) > 0 ? a : b;
    const smaller = a.cmp(b) > 0 ? b : a;
    return choiceItem(
      {
        templateId: 'M.FR.COMPARE.pair',
        objectiveId: 'M.FR.COMPARE',
        seed: 0,
        stem: `Which is bigger, 1/${d1} or 1/${d2}?`,
        working: [
          { say: `Cut a cake into ${d1} pieces, and another into ${d2} pieces.` },
          { say: `More pieces means each one is smaller.` },
          { say: `= ${bigger.toString()}` },
        ],
        options: [
          { label: bigger.toString(), correct: true },
          { label: smaller.toString(), correct: false, misconceptionId: 'denominator-magnitude' },
        ],
      },
      rng
    );
  }),

  t('M.FR.COMPARE.unlike', 'M.FR.COMPARE', 4, 2, (rng) => {
    const d1 = rng.pick([3, 4, 5, 6, 8]);
    let d2 = rng.pick([3, 4, 5, 6, 8, 9, 10, 12]);
    while (d2 === d1) d2 = rng.pick([3, 4, 5, 6, 8, 9, 10, 12]);
    const n1 = rng.int(1, d1 - 1);
    let n2 = rng.int(1, d2 - 1);
    const a = new Rational(n1, d1);
    let b = new Rational(n2, d2);
    let guard = 0;
    while (a.eq(b) && guard++ < 20) {
      n2 = rng.int(1, d2 - 1);
      b = new Rational(n2, d2);
    }
    if (a.eq(b)) b = new Rational(Math.max(1, n2 - 1), d2);
    const l = lcm(d1, d2);
    const bigger = a.cmp(b) > 0 ? a : b;
    const smaller = a.cmp(b) > 0 ? b : a;
    const biggerLabel = bigger.eq(a) ? `${n1}/${d1}` : `${b.n}/${b.d}`;
    const smallerLabel = bigger.eq(a) ? `${b.n}/${b.d}` : `${n1}/${d1}`;
    return choiceItem(
      {
        templateId: 'M.FR.COMPARE.unlike',
        objectiveId: 'M.FR.COMPARE',
        seed: 0,
        stem: `Which is bigger, ${n1}/${d1} or ${b.n}/${b.d}?`,
        working: [
          { say: `Both bottoms go into ${l}.` },
          { say: `${n1}/${d1} = ${(l / d1) * n1}/${l} and ${b.n}/${b.d} = ${(l / b.d) * b.n}/${l}.` },
          { say: `Now the tops can be compared. = ${biggerLabel}` },
        ],
        options: [
          { label: biggerLabel, correct: true },
          {
            label: smallerLabel,
            correct: false,
            // Judge the misconception from the fractions as written, not as
            // simplified, because the written form is what she is looking at.
            misconceptionId: writtenDen(smallerLabel) > writtenDen(biggerLabel)
              ? 'denominator-magnitude'
              : writtenNum(smallerLabel) > writtenNum(biggerLabel)
                ? 'numerator-only'
                : 'gap-thinking',
          },
        ],
      },
      rng
    );
  }),

  t('M.FR.ADD.unlike', 'M.FR.ADD', 3, 0, (rng) => {
    const d1 = rng.pick([2, 3, 4, 5, 6]);
    let d2 = rng.pick([2, 3, 4, 5, 6, 8, 10]);
    let guard = 0;
    while ((d2 === d1 || lcm(d1, d2) > 40) && guard++ < 30) d2 = rng.pick([2, 3, 4, 5, 6, 8, 10]);
    const n1 = rng.int(1, d1 - 1);
    const n2 = rng.int(1, d2 - 1);
    const a = new Rational(n1, d1);
    const b = new Rational(n2, d2);
    const answer = a.add(b);
    const l = lcm(d1, d2);
    return {
      templateId: 'M.FR.ADD.unlike',
      objectiveId: 'M.FR.ADD',
      seed: 0,
      input: 'fraction',
      stem: `${n1}/${d1} + ${n2}/${d2} = ?`,
      note: 'Give your answer in its simplest form.',
      canonical: answer.toString(),
      working: [
        { say: `The bottoms are different, so make them match. Both go into ${l}.` },
        { say: `${n1}/${d1} = ${(l / d1) * n1}/${l} and ${n2}/${d2} = ${(l / d2) * n2}/${l}.` },
        { say: `Add the tops only: ${(l / d1) * n1} + ${(l / d2) * n2} = ${(l / d1) * n1 + (l / d2) * n2}.` },
        { say: `= ${answer.toString()}` },
      ],
      mark: markNumeric(answer, {
        requireSimplest: true,
        traps: [
          { value: `${n1 + n2}/${d1 + d2}`, misconceptionId: 'add-both' },
          { value: `${n1 + n2}/${d1}`, misconceptionId: 'kept-first-denominator' },
        ],
      }),
    };
  }),

  t('M.FR.ADD.subtract', 'M.FR.ADD', 4, 1, (rng) => {
    const d1 = rng.pick([2, 3, 4, 5, 6]);
    let d2 = rng.pick([3, 4, 5, 6, 8, 10]);
    let guard = 0;
    while ((d2 === d1 || lcm(d1, d2) > 40) && guard++ < 30) d2 = rng.pick([3, 4, 5, 6, 8, 10]);
    let n1 = rng.int(1, d1 - 1);
    let n2 = rng.int(1, d2 - 1);
    let a = new Rational(n1, d1);
    let b = new Rational(n2, d2);
    if (a.cmp(b) <= 0) {
      [a, b] = [b, a];
      [n1, n2] = [n2, n1];
    }
    const answer = a.sub(b);
    const l = lcm(a.d, b.d);
    return {
      templateId: 'M.FR.ADD.subtract',
      objectiveId: 'M.FR.ADD',
      seed: 0,
      input: 'fraction',
      stem: `${a.n}/${a.d} − ${b.n}/${b.d} = ?`,
      note: 'Give your answer in its simplest form.',
      canonical: answer.toString(),
      working: [
        { say: `Both bottoms go into ${l}.` },
        { say: `${a.n}/${a.d} = ${(l / a.d) * a.n}/${l} and ${b.n}/${b.d} = ${(l / b.d) * b.n}/${l}.` },
        { say: `Take the tops: ${(l / a.d) * a.n} − ${(l / b.d) * b.n} = ${(l / a.d) * a.n - (l / b.d) * b.n}.` },
        { say: `= ${answer.toString()}` },
      ],
      mark: markNumeric(answer, {
        requireSimplest: true,
        traps: [
          ...(a.d !== b.d ? [{ value: `${a.n - b.n}/${a.d - b.d || 1}`, misconceptionId: 'add-both' }] : []),
          { value: `${a.n - b.n}/${a.d}`, misconceptionId: 'kept-first-denominator' },
        ],
      }),
    };
  }),

  t('M.FR.MIXED.improper', 'M.FR.MIXED', 3, 0, (rng) => {
    const d = rng.pick([3, 4, 5, 6, 8]);
    const whole = rng.int(1, 4);
    const rem = rng.int(1, d - 1);
    const n = whole * d + rem;
    const answer = new Rational(n, d);
    return {
      templateId: 'M.FR.MIXED.improper',
      objectiveId: 'M.FR.MIXED',
      seed: 0,
      input: 'text',
      stem: `Write ${n}/${d} as a mixed number.`,
      note: 'Like this: 2 1/3',
      canonical: answer.toMixed(),
      working: [
        { say: `How many whole ones fit? Divide, do not subtract.` },
        { say: `${n} ÷ ${d} = ${whole} remainder ${rem}.` },
        { say: `So that is ${whole} whole ones and ${rem}/${d} left over.` },
        ...(new Rational(rem, d).toString() === `${rem}/${d}`
          ? []
          : [{ say: `${rem}/${d} simplifies to ${new Rational(rem, d).toString()}.` }]),
        { say: `= ${answer.toMixed()}` },
      ],
      mark: markNumeric(answer, {
        alsoAccept: [answer.toMixed()],
        traps: [
          { value: `${n - d}/${d}`, misconceptionId: 'subtract-not-divide' },
          { value: `${rem}/${d}`, misconceptionId: 'lost-the-whole' },
        ],
      }),
    };
  }),

  t('M.FR.MULT.pair', 'M.FR.MULT', 3, 0, (rng) => {
    const d1 = rng.pick([2, 3, 4, 5, 6]);
    const d2 = rng.pick([2, 3, 4, 5, 7, 8]);
    const n1 = rng.int(1, d1 - 1);
    const n2 = rng.int(1, d2 - 1);
    const a = new Rational(n1, d1);
    const b = new Rational(n2, d2);
    const answer = a.mul(b);
    const cross = new Rational(n1 * d2, d1 * n2);
    return {
      templateId: 'M.FR.MULT.pair',
      objectiveId: 'M.FR.MULT',
      seed: 0,
      input: 'fraction',
      stem: `${n1}/${d1} × ${n2}/${d2} = ?`,
      note: 'Give your answer in its simplest form.',
      canonical: answer.toString(),
      working: [
        { say: `Tops times tops: ${n1} × ${n2} = ${n1 * n2}.` },
        { say: `Bottoms times bottoms: ${d1} × ${d2} = ${d1 * d2}.` },
        {
          say:
            `${n1 * n2}/${d1 * d2}` === answer.toString()
              ? `${n1 * n2}/${d1 * d2} is already in its simplest form.`
              : `${n1 * n2}/${d1 * d2} simplifies to ${answer.toString()}.`,
        },
      ],
      mark: markNumeric(answer, {
        requireSimplest: true,
        traps: [
          { value: a.add(b).toString(), misconceptionId: 'added-instead' },
          ...(!cross.eq(answer) ? [{ value: cross.toString(), misconceptionId: 'cross-multiply' }] : []),
        ],
      }),
    };
  }),

  t('M.FR.DIV.bywhole', 'M.FR.DIV', 4, 0, (rng) => {
    const d = rng.pick([2, 3, 4, 5, 6, 7]);
    const n = rng.int(1, d - 1);
    const k = rng.int(2, 6);
    const a = new Rational(n, d);
    const answer = a.div(new Rational(k));
    return {
      templateId: 'M.FR.DIV.bywhole',
      objectiveId: 'M.FR.DIV',
      seed: 0,
      input: 'fraction',
      stem: `${n}/${d} ÷ ${k} = ?`,
      note: 'Give your answer in its simplest form.',
      canonical: answer.toString(),
      working: [
        { say: `Sharing ${n}/${d} between ${k} makes the pieces smaller.` },
        { say: `Smaller pieces means a bigger bottom number: ${d} × ${k} = ${d * k}.` },
        ...(`${n}/${d * k}` === answer.toString()
          ? []
          : [{ say: `${n}/${d * k} simplifies to ${answer.toString()}.` }]),
        { say: `= ${answer.toString()}` },
      ],
      mark: markNumeric(answer, {
        requireSimplest: true,
        traps: [
          { value: a.mul(new Rational(k)).toString(), misconceptionId: 'multiplied-instead' },
          ...(n % k === 0 ? [{ value: `${n / k}/${d}`, misconceptionId: 'divided-numerator' }] : []),
        ],
      }),
    };
  }),

  // ============================================================ operations
  t('M.OPS.ORDER.mixed', 'M.OPS.ORDER', 3, 0, (rng) => {
    const a = rng.int(2, 12);
    const b = rng.int(2, 9);
    const c = rng.int(2, 9);
    const d = rng.int(2, 12);
    const shape = rng.int(0, 2);
    let stem: string, answer: number, ltr: number, steps: string[];
    if (shape === 0) {
      stem = `${a} + ${b} × ${c}`;
      answer = a + b * c;
      ltr = (a + b) * c;
      steps = [`Multiply first: ${b} × ${c} = ${b * c}.`, `Then add: ${a} + ${b * c} = ${answer}.`];
    } else if (shape === 1) {
      stem = `(${a} + ${b}) × ${c}`;
      answer = (a + b) * c;
      ltr = a + b * c;
      steps = [`Brackets first: ${a} + ${b} = ${a + b}.`, `Then multiply: ${a + b} × ${c} = ${answer}.`];
    } else {
      stem = `${d} − ${b} × ${c}`;
      answer = d - b * c;
      ltr = (d - b) * c;
      steps = [`Multiply first: ${b} × ${c} = ${b * c}.`, `Then subtract: ${d} − ${b * c} = ${answer}.`];
    }
    return {
      templateId: 'M.OPS.ORDER.mixed',
      objectiveId: 'M.OPS.ORDER',
      seed: 0,
      input: 'number',
      stem: `${stem} = ?`,
      canonical: String(answer),
      working: [
        { say: `Brackets, then multiply and divide, then add and subtract.` },
        ...steps.map((s) => ({ say: s })),
      ],
      mark: markNumeric(new Rational(answer), {
        traps: [{ value: String(ltr), misconceptionId: shape === 1 ? 'brackets-ignored' : 'left-to-right' }],
      }),
    };
  }),

  t('M.OPS.LONGMULT.four', 'M.OPS.LONGMULT', 4, 0, (rng) => {
    const a = rng.int(1200, 9899);
    const b = rng.int(13, 89);
    const answer = a * b;
    const units = b % 10;
    const tens = Math.floor(b / 10);
    const missingZero = a * units + a * tens;
    return {
      templateId: 'M.OPS.LONGMULT.four',
      objectiveId: 'M.OPS.LONGMULT',
      seed: 0,
      input: 'number',
      stem: `${commas(a)} × ${b} = ?`,
      note: 'Use a written method. Paper is fine, just type the answer.',
      canonical: commas(answer),
      working: [
        { say: `Split ${b} into ${tens} tens and ${units} units.` },
        { say: `${commas(a)} × ${units} = ${commas(a * units)}` },
        { say: `${commas(a)} × ${tens} tens = ${commas(a * tens * 10)}  (note the zero on the end)` },
        { say: `${commas(a * units)} + ${commas(a * tens * 10)} = ${commas(answer)}` },
      ],
      mark: markNumeric(new Rational(answer), {
        traps: [{ value: String(missingZero), misconceptionId: 'missing-zero' }],
      }),
    };
  }),

  t('M.OPS.DIV.coaches', 'M.OPS.DIV', 4, 2, (rng) => {
    const per = rng.pick([28, 32, 36, 45, 48, 52]);
    const groups = rng.int(3, 12);
    const extra = rng.int(1, per - 1);
    const total = per * groups + extra;
    const answer = groups + 1;
    const thing = rng.pick([
      { unit: 'coaches', people: 'children', verb: 'holds', setup: 'are going on a school trip' },
      { unit: 'minibuses', people: 'passengers', verb: 'seats', setup: 'are travelling to the match' },
      { unit: 'tables', people: 'guests', verb: 'seats', setup: 'are coming to the hall' },
    ]);
    return {
      templateId: 'M.OPS.DIV.coaches',
      objectiveId: 'M.OPS.DIV',
      seed: 0,
      input: 'number',
      stem: `${commas(total)} ${thing.people} ${thing.setup}. Each of the ${thing.unit} ${thing.verb} ${per}.\n\nHow many ${thing.unit} are needed?`,
      canonical: String(answer),
      working: [
        { say: `${commas(total)} ÷ ${per} = ${groups} remainder ${extra}.` },
        { say: `${groups} ${thing.unit} would leave ${extra} ${thing.people} behind.` },
        { say: `So you need one more: ${answer}.` },
      ],
      mark: markNumeric(new Rational(answer), {
        traps: [
          { value: String(groups), misconceptionId: 'wrong-rounding' },
          { value: String(extra), misconceptionId: 'dropped-remainder' },
        ],
      }),
    };
  }),

  // ============================================================ percentages and ratio
  t('M.PCT.EQUIV.todecimal', 'M.PCT.EQUIV', 3, 0, (rng) => {
    const pair = rng.pick([
      [1, 2], [1, 4], [3, 4], [1, 5], [2, 5], [3, 5], [4, 5],
      [1, 8], [3, 8], [5, 8], [7, 8], [1, 10], [3, 10], [7, 10], [9, 10], [1, 20], [3, 20],
    ]);
    const r = new Rational(pair[0], pair[1]);
    const dec = r.toDecimal()!;
    return {
      templateId: 'M.PCT.EQUIV.todecimal',
      objectiveId: 'M.PCT.EQUIV',
      seed: 0,
      input: 'number',
      stem: `Write ${pair[0]}/${pair[1]} as a decimal.`,
      canonical: dec,
      working: [
        { say: `A fraction is a division: ${pair[0]} ÷ ${pair[1]}.` },
        { say: `${pair[0]} ÷ ${pair[1]} = ${dec}` },
      ],
      mark: markNumeric(r, {
        traps: [{ value: `0.${pair[0]}${pair[1]}`, misconceptionId: 'literal-digits' }],
      }),
    };
  }),

  t('M.PCT.EQUIV.tofraction', 'M.PCT.EQUIV', 3, 1, (rng) => {
    const pct = rng.pick([5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 64, 75, 80, 90]);
    const answer = new Rational(pct, 100);
    return {
      templateId: 'M.PCT.EQUIV.tofraction',
      objectiveId: 'M.PCT.EQUIV',
      seed: 0,
      input: 'fraction',
      stem: `Write ${pct}% as a fraction.`,
      note: 'In its simplest form.',
      canonical: answer.toString(),
      working: [
        { say: `Per cent means out of a hundred, so ${pct}% = ${pct}/100.` },
        { say: `Now simplify: divide top and bottom by ${gcd(pct, 100)}.` },
        { say: `= ${answer.toString()}` },
      ],
      mark: markNumeric(answer, {
        requireSimplest: true,
        traps: [{ value: `${pct}/10`, misconceptionId: 'decimal-point-shift' }],
      }),
    };
  }),

  t('M.PCT.OF.money', 'M.PCT.OF', 3, 2, (rng) => {
    const pct = rng.pick([5, 10, 15, 20, 25, 30, 40, 50, 60, 75]);
    const pounds = rng.int(4, 180);
    const amount = new Rational(pounds * 100, 100);
    const answer = amount.mul(new Rational(pct, 100));
    const thing = rng.pick(['a coat', 'a bike', 'a game', 'a pair of boots', 'a tent', 'a bag']);
    return {
      templateId: 'M.PCT.OF.money',
      objectiveId: 'M.PCT.OF',
      seed: 0,
      input: 'number',
      stem: `${thing[0].toUpperCase() + thing.slice(1)} costs ${money(amount)}. There is ${pct}% off in the sale.\n\nHow much money do you save?`,
      note: 'Answer in pounds, like 12.50',
      canonical: money(answer),
      working: percentageWorking(amount, pct, answer),
      mark: markNumeric(answer, {
        traps: [
          { value: String(pct), misconceptionId: 'percent-as-whole' },
          { value: amount.div(new Rational(100)).toDecimal() ?? '0', misconceptionId: 'wrong-tenth' },
        ],
      }),
    };
  }),

  t('M.RAT.SCALE.recipe', 'M.RAT.SCALE', 3, 2, (rng) => {
    const forPeople = rng.pick([2, 3, 4, 5, 6]);
    const k = rng.int(2, 5);
    const people = forPeople * k;
    const qty = rng.int(2, 12);
    const answer = qty * k;
    const item = rng.pick([
      { name: 'eggs', unit: '' },
      { name: 'grams of flour', unit: 'g' },
      { name: 'millilitres of milk', unit: 'ml' },
    ]);
    const q = item.unit === 'g' ? qty * 25 : item.unit === 'ml' ? qty * 20 : qty;
    const a = item.unit === 'g' ? answer * 25 : item.unit === 'ml' ? answer * 20 : answer;
    return {
      templateId: 'M.RAT.SCALE.recipe',
      objectiveId: 'M.RAT.SCALE',
      seed: 0,
      input: 'number',
      stem: `A recipe for ${forPeople} people uses ${q} ${item.name}.\n\nHow much do you need for ${people} people?`,
      note: item.unit ? `Answer in ${item.unit === 'g' ? 'grams' : 'millilitres'}.` : 'Answer as a number.',
      canonical: String(a),
      working: [
        { say: `${people} ÷ ${forPeople} = ${k}, so it is ${k} times as many people.` },
        { say: `Ask how many times bigger, not how many more.` },
        { say: `${q} × ${k} = ${a}` },
      ],
      mark: markNumeric(new Rational(a), {
        traps: [
          { value: String(q + (people - forPeople)), misconceptionId: 'additive-comparison' },
          ...(k !== 1 ? [{ value: String(Math.round(q / k)), misconceptionId: 'inverted-ratio' }] : []),
        ],
      }),
    };
  }),
];

// ---------------------------------------------------------------- helpers

function divisorsOf(n: number): number[] {
  const out: number[] = [];
  for (let i = 1; i <= n; i++) if (n % i === 0) out.push(i);
  return out;
}

function smallestFactor(n: number): number {
  for (let i = 2; i * i <= n; i++) if (n % i === 0) return i;
  return n;
}

function nearestNonFactor(n: number, rng: RNG): number {
  for (let tries = 0; tries < 40; tries++) {
    const c = rng.int(2, Math.max(3, Math.floor(n / 2)));
    if (n % c !== 0) return c;
  }
  return 7;
}

function listMultiples(x: number, upTo: number): string {
  const out: number[] = [];
  for (let k = 1; x * k <= upTo && out.length < 14; k++) out.push(x * k);
  const shown = out.join(', ');
  return out[out.length - 1] === upTo ? shown : shown + ', …';
}

function writtenNum(label: string): number {
  return parseInt(label.split('/')[0], 10);
}
function writtenDen(label: string): number {
  return parseInt(label.split('/')[1] ?? '1', 10);
}

function percentageWorking(amount: Rational, pct: number, answer: Rational) {
  const ten = amount.div(new Rational(10));
  const five = ten.div(new Rational(2));
  const steps: { say: string }[] = [{ say: `10% of ${money(amount)} is ${money(ten)}.` }];
  if (pct % 10 === 0) {
    steps.push({ say: `${pct}% is ${pct / 10} lot${pct / 10 === 1 ? '' : 's'} of 10%.` });
  } else {
    steps.push({ say: `5% is half of that: ${money(five)}.` });
    const tens = Math.floor(pct / 10);
    steps.push({
      say: tens === 0
        ? `${pct}% is that 5%.`
        : `${pct}% is ${tens} lot${tens === 1 ? '' : 's'} of 10% plus one 5%.`,
    });
  }
  steps.push({ say: `= ${money(answer)}` });
  return steps;
}

function ordinalWord(i: number): string {
  return ['first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh'][i] ?? String(i + 1) + 'th';
}

function columnName(powerOfTen: number): string {
  return (
    ['units', 'tens', 'hundreds', 'thousands', 'ten thousands', 'hundred thousands', 'millions'][
      powerOfTen
    ] ?? `10^${powerOfTen}`
  );
}
